### ISSUE TITLE
Add support to Valine

### ISSUE THREAD

**Issue by czruby** [Tong-H/hexo-theme-energy#2]
Valine is a useful tool to add comment service to the blog. So can we add support to Valine in this theme?
Your theme is so pretty!

**Comment by Tong-H** [comment]
Valine looks great and is easy to use. but, it seems like the author has stopped supporting it. because [dashboard](https://leancloud.cn/dashboard/login.html#/signup)  can't open, and a lot of issues remain unresolved.

**Comment by czruby** [comment]
> Valine looks great and is easy to use. but, it seems like the author has stopped supporting it. because [dashboard](https://leancloud.cn/dashboard/login.html#/signup) can't open, and a lot of issues remain unresolved.

The dashboard url was updated to  [dashboard](https://console.leancloud.cn/login)
And what a pity that it has stopped updated since 2022. But yesterday I have added it to my own hexo blog, and it seems that it can still be used.

**Comment by Tong-H** [comment]
I've tried it, and yes, it works great. I've added it to the theme, so once you update the repo, it should work for you

**Comment by czruby** [comment]
Thank you very much. And I have to say again that your theme are so beatiful that I like it very much!
